
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        this is the page
      </body>
    </html>
  );
}

export const metadata = {
  title: "This is the dashboard page",
  description: "Generated by create next app",
};
